// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lczlirvjjmwgblrfgaxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjemxpcnZqam13Z2JscmZnYXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODk3MDYsImV4cCI6MjA2NTU2NTcwNn0.RaKVEkUbIlJiFjgqk07rCgaoANo9En-Bjb95QAPQCeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);